name: preprocessing-automation

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "Eksperimen_SML_Rivaldo Angelo"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Debug (cek file)
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type f -name "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Rivaldo.py \
            --raw_path spiderman_youtube_review_raw/spiderman_youtube_review_raw.csv \
            --output_dir preprocessing/spiderman_youtube_review_preprocessing

      - name: Upload preprocessed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: spiderman_youtube_review_preprocessed
          path: "Eksperimen_SML_Rivaldo Angelo/preprocessing/spiderman_youtube_review_preprocessing/spiderman_youtube_review_preprocessed.csv"
